# Generated by Django 2.1.3 on 2018-11-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ficheros',
            fields=[
                ('id_fichero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_mensaje', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PalabrasClave',
            fields=[
                ('palabra', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('id_proyecto', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre_usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contrasenya', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_usuarios', to='app.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_proyecto', to='app.Usuarios'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_proyecto', to='app.Usuarios'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_proyecto', to='app.Usuarios'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_proyecto', to='app.Estado'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_notificaciones', to='app.Usuarios'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para_notificaciones', to='app.Usuarios'),
        ),
        migrations.AddField(
            model_name='ficheros',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_ficheros', to='app.Usuarios'),
        ),
    ]
