# Generated by Django 2.1.3 on 2018-11-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabrasClaveProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabra_palabrasclaveproyecto', to='app.PalabrasClave')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_palabrasclaveproyecto', to='app.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoFichero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichero_proyectofichero', to='app.Ficheros')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_proyectofichero', to='app.Proyecto')),
            ],
        ),
    ]
